# Generated by Django 4.2.16 on 2025-01-31 18:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cliente_produto_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=15, verbose_name='C.P.F'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='datanasc',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 18, 45, 25, 29563), verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.produto'),
        ),
    ]
