# Generated by Django 4.2.16 on 2025-02-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_itempedido_pedido_itempedido_pedido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='preco_unitario',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qtde',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table=None,
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Cartão'), (3, 'Pix'), (4, 'Outra')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pgto', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pedido')),
            ],
        ),
    ]
