# Generated by Django 4.2.16 on 2025-02-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_itempedido_preco_unitario_itempedido_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma',
            field=models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Credito'), (3, 'Debito'), (4, 'Pix'), (5, 'Ticket'), (6, 'Outra')]),
        ),
    ]
